import type { Metadata } from "next"
import { Manrope } from "next/font/google"
import { cn } from "../lib/utils"

import "@repo/modules/globals.css"
import "../styles/globals.css"

const manrope = Manrope({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={cn("flex flex-col h-screen", manrope.className)}>
        {children}
      </body>
    </html>
  )
}
